#use_frameworks!

target 'MTQRCodeScanner_Example' do
  pod 'MTQRCodeScanner', :path => '../'

  target 'MTQRCodeScanner_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
